apiVersion: v1
kind: Service
metadata:
  name: nexus-docker
  namespace: nexus
spec:
  selector:
    app: nexus
  ports:
    - name: docker
      port: 5000
      targetPort: 5000
      protocol: TCP
