spring:
  application:
    name: commandes-service
  datasource:
    url: jdbc:mysql://localhost:3306/commandes_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:  # mettre ton mot de passe ou laisser vide si local sans mdp
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8081

logging:
  level:
    order_tracking.Commandes: INFO
    org.springframework: WARN
