spring:
  application:
    name: service-utilisateur
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:  # idem
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8082

logging:
  level:
    order_tracking.Users: INFO
    org.springframework: WARN

jwt:
  secret: "dHJlc19sb25ndWUtc2VjcmV0LWtleS1lbmNvZGVkLWluLUI2NA=="
  expiration: 86400000  # 24h en ms
