spring:
  datasource:
    url: jdbc:mysql://mysql:3306/commandesdb
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          enabled: false

  kafka:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://service-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8081

