apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-service-commande
spec:
  params:
    - name: url
    - name: revision
    - name: contextDir
    - name: image
    - name: tag

  workspaces:
    - name: shared

  tasks:

    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared
          workspace: shared

    - name: build
      runAfter:
        - clone
      taskRef:
        name: maven-build
      params:
        - name: contextDir
          value: $(params.contextDir)
      workspaces:
        - name: shared
          workspace: shared

    - name: image
      runAfter:
        - build
      taskRef:
        name: build-image
      params:
        - name: IMAGE
          value: $(params.image):$(params.tag)
      workspaces:
        - name: source
          workspace: shared
