apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-service-commande
  namespace: ci
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: master
    - name: CONTEXT_DIR
      type: string
      default: .
    - name: image
      type: string
    - name: tag
      type: string
      default: latest

  workspaces:
    - name: shared
    - name: maven-repo

  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared
          workspace: shared

    - name: build
      runAfter:
        - clone
      taskRef:
        name: maven-build
      params:
        - name: CONTEXT_DIR
          value: $(params.CONTEXT_DIR)
      workspaces:
        - name: source
          workspace: shared
        - name: maven-repo
          workspace: maven-repo

    - name: image
      runAfter:
        - build
      taskRef:
        name: build-image
      params:
        - name: contextDir
          value: $(params.CONTEXT_DIR)
        - name: image
          value: $(params.image)
      workspaces:
        - name: shared
          workspace: shared

