apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-service-commande
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
    - name: contextDir
      type: string
    - name: image
      type: string
    - name: tag
      type: string

  workspaces:
    - name: shared
    - name: maven-repo
    - name: maven-settings

  tasks:

    # -----------------------------
    # 1️⃣ CLONE GIT
    # -----------------------------
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared
          workspace: shared

    # -----------------------------
    # 2️⃣ BUILD MAVEN
    # -----------------------------
    - name: build
      taskRef:
        name: maven-build
      runAfter:
        - clone
      params:
        - name: contextDir
          value: $(params.contextDir)
      workspaces:
        - name: shared
          workspace: shared
        - name: maven-repo
          workspace: maven-repo
        - name: maven-settings
          workspace: maven-settings

    # -----------------------------
    # 3️⃣ BUILD DOCKER IMAGE (KANIKO)
    # -----------------------------
    - name: docker
      taskRef:
        name: kaniko-build
      runAfter:
        - build
      params:
        # 🔥 IMPORTANT : respecter EXACTEMENT le nom du dossier
        - name: contextDir
          value: $(params.contextDir)

        - name: image
          value: $(params.image):$(params.tag)
      workspaces:
        - name: shared
          workspace: shared
