apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: run-service-commande
  namespace: ci
spec:
  taskRunTemplate:
    serviceAccountName: pipeline

  pipelineRef:
    name: pipeline-service-commande

  params:
    - name: url
      value: https://github.com/Sabrynette/BACKEND-FINAL.git
    - name: revision
      value: master
    - name: CONTEXT_DIR
      value: repo/Commandes
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ci/service-commande:latest
    - name: tag
      value: latest

  workspaces:
    - name: shared
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
      subPath: source

    - name: maven-repo
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
      subPath: maven-repo


