apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: run-service-notification
  namespace: ci-pipeline
spec:
  pipelineRef:
    name: pipeline-microservice
  params:
    - name: url
      value: https://github.com/Sabrynette/BACKEND-PROJECT.git
    - name: contextDir
      value: service-notification
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/ci-pipeline/service-notification:latest
  workspaces:
    - name: shared
      emptyDir: {}
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pvc
    - name: maven-settings
      configMap:
        name: maven-settings
